### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by qonto-android-team** [BoD/app-store-rating-rss#1]
NPE when requesting the RSS for Qonto : https://app-store-rating-rss.herokuapp.com/googlePlayStore/eu.qonto.qonto?friendlyName=Qonto&noStoreLink=true

please fix ! :)

**Comment by BoD** [comment]
Resolved via https://github.com/BoD/klibappstorerating/commit/2447acabde1553f0a5e4b1257d593d26e35a1cac. 

No idea why the rating is suddenly absent when country is Ireland (where the Heroku instance is running) `¯\_(ツ)_/¯`

**Comment by qonto-android-team** [comment]
Thanks Bod ❤️
